//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminSystem
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please enter user!")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter password!")]
        public string UserPassword { get; set; }
        public string RoleSystem { get; set; }
        public Nullable<bool> isStatus { get; set; }
    }
}
