//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Borrows = new HashSet<Borrow>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_pub { get; set; }
        public Nullable<int> Id_loc { get; set; }
        public Nullable<int> Id_shelf { get; set; }
        public Nullable<int> Id_lan { get; set; }
        public Nullable<int> Id_cate { get; set; }
        public Nullable<int> Id_author { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> Pages { get; set; }
        public string keyword { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string images { get; set; }
        public string Isbn { get; set; }
        public string Note { get; set; }
        public Nullable<bool> isStatus { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
        public virtual Location Location { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Shelf Shelf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrows { get; set; }
    }
}
